name: Next.js Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.0
        
    - name: Setup PNPM
      uses: pnpm/setup-pnpm@v6  
      with:
        version: 8.11.0
        
    - name: SSH into EC2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        if: success()
        script: |
          cd /home/b2btools/htdocs/b2btools.humdash.com
          pnpm i
          pnpm lint || exit 1
          
